### ISSUE TITLE
.mixin-justify-content(space-between) - produces doubled  -ms-flex-pack property

### ISSUE THREAD

**Issue by olexme** [annebosman/FlexboxLess#2]
The issue is in doubled the same rules for IE10:
.mixin-justify-content(@justify) when (@justify = space-between) {
    -ms-flex-pack: justify;
}
.mixin-justify-content(@justify) when (@justify = space-between) {
    -ms-flex-pack: distribute;
}

The second one is not necessery and in fact doesn't work.

**Comment by annebosman** [comment]
Fixed on master
